### PR TITLE
Skip injecting extensions on frame switch to prevent javascript errors

### LINKED ISSUE #200: Javascript errors triggered by cuprite on pages with iframes
On pages with iframes cuprite triggers a javascript error when switching into a frame.

I have written a test which shows the errors:

```diff
diff --git a/spec/features/driver_spec.rb b/spec/features/driver_spec.rb
index d9f9403..d4c3d7d 100644
--- a/spec/features/driver_spec.rb
+++ b/spec/features/driver_spec.rb
@@ -1555,6 +1555,16 @@ module Capybara
         expect(@session.driver.current_url).to end_with("/cuprite/frames")
       end

+      it "generates no javascript errors with frames" do
+        @driver.browser.evaluate_on_new_document(
+          "window.errors ||= []; window.onerror = function(msg) { window.errors += msg; };" 
+        )
+        @session.visit "/cuprite/frames" 
+
+        @session.within_frame(0) { expect(@session.evaluate_script("window.errors")).to be_empty }
+        expect(@session.evaluate_script("window.errors")).to be_empty
+      end
+
       it "waits for network idle" do
         @session.visit "/cuprite/show_cookies" 
         expect(@session).not_to have_content("test_cookie")
```

This fails with this message:

```
Failure/Error: @session.within_frame(0) { expect(@session.evaluate_script("window.errors")).to be_empty }                 
  expected `"Uncaught SyntaxError: Identifier 'InvalidSelector' has already been declared".empty?` to be truthy, got false
```

However this seems only to happen with Chrome >= 102. When i run this test with Chrome 101 or lower it does not fail.

The identifier `InvalidSelector` is defined here: https://github.com/rubycdp/cuprite/blob/2bbf3634d92af4e8b8ec3026c2b66ccf1d0590ad/lib/capybara/cuprite/javascripts/index.js.
Looks like these extensions are executed in the same context multiple times with frames?

### PR DESCRIPTION
**Pull request by hoffi**
Fixes #200.

The extensions were injected again on every frame switch. That seemed unnecessary to me as they were already injected on page load by ferrum.
This resulted in some javascript errors, because some constants were redefined by the default cuprite extension.

This change fixes this problem and there does not seem to be anything missing inside the frames.

### CODE REVIEW

**Comment by route** [comment]
This was exactly the issue in the past as they weren't injected, in other words this is a workaround, I'll double check if Chrome fixed this.

Seems like this test isn't accurate because it doesn't check if there are extensions available in the frame.

**Comment by hoffi** [comment]
Any info on this?

Or should this be handled in ferrum?
We could track all loaded extensions there and only execute them when they are not in the list.
Something like this [here](https://github.com/rubycdp/ferrum/blob/0d1b3e90f1b9bb0d3dcdbea8e2068ee78c254ab0/lib/ferrum/page.rb#L449) and [here](https://github.com/rubycdp/ferrum/blob/0d1b3e90f1b9bb0d3dcdbea8e2068ee78c254ab0/lib/ferrum/page.rb#L473):
```ruby
extension_digest = Digest::SHA256.hexdigest(extension)
extension_wrapper = <<~JS
  window._ferrum_loaded_extensions ||= [];
  if (window._ferrum_loaded_extensions.indexOf("#{extension_digest}") == -1) {
    window._ferrum_loaded_extensions.push("#{extension_digest}");
    #{extension}
  }
JS
command("Page.addScriptToEvaluateOnNewDocument", source: extension_wrapper)
[...]
```

File: spec/features/session_spec.rb [hunk 1]
```diff
@@ -826,6 +826,18 @@
           expect(e).to be_a(Capybara::ElementNotFound)
         end)
       end
+
+      it "generates no javascript errors when switching into a frame" do
+        @driver.browser.evaluate_on_new_document(
```
Comment (myabc) [inline spec/features/session_spec.rb:831]:
```suggestion
      @session.driver.browser.evaluate_on_new_document(
```
